version: '{build}'
skip_tags: true
environment:
  # The default cpack in the PATH is not CMake
  CPACK: C:\Program Files (x86)\CMake\bin\cpack.exe
  matrix:
  - TARGET: MINGW_64
    BUILD_DEPS_SCRIPT: .ci\msys_build_deps.bat
    BUILD_SCRIPT: .ci\msys_build.bat
  - TARGET: MINGW_32
    BUILD_DEPS_SCRIPT: .ci\msys_build_deps.bat
    BUILD_SCRIPT: .ci\msys_build.bat
install: []
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
- if defined BUILD_DEPS_SCRIPT call %BUILD_DEPS_SCRIPT%
- call %BUILD_SCRIPT%
# Build artifacts
- cd build
- '"%CPACK%" -G NSIS -C Release'
- '"%CPACK%" -G ZIP -C Release'
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
artifacts:
- path: build/Neovim.zip
